// src/components/ModelCard.vue
<template>
  <q-card 
    class="model-card q-ma-md"
    :class="cardClass"
    style="width: 100%; max-width: 500px;"
  >
    <q-card-section class="card-header">
      <div class="row items-center justify-between">
        <div>
          <div class="text-h6 text-weight-bold">{{ model.name }}</div>
          <div class="text-subtitle2">{{ model.category }}</div>
        </div>
        <q-btn
          flat
          round
          icon="search"
          @click="google(model)"
          :color="isYellowCard ? 'dark' : 'white'"
        >
          <q-tooltip>Search on Google</q-tooltip>
        </q-btn>
      </div>
    </q-card-section>
    
    <q-separator />
    
    <q-card-section class="description bg-grey-1 text-dark">
      <div class="text-body1" style="white-space: pre-wrap;">
        {{ model.description }}
      </div>
    </q-card-section>
    
    <q-card-actions class="bg-grey-1 justify-between">
      <q-btn 
        flat 
        label="Back" 
        color="primary"
        @click="previousModel()"
      />
      <q-btn 
        flat 
        label="Next" 
        color="primary"
        @click="nextModel()"
      />
    </q-card-actions>
  </q-card>
</template>

<script>
import { computed } from 'vue'

export default {
  name: 'ModelCard',
  props: {
    model: {
      type: Object,
      required: true
    }
  },
  emits: ['onNext', 'onPrevious'],
  setup(props, { emit }) {
    const cardClass = computed(() => {
      const categoryClasses = {
        'Logical Fallacies': 'cyan-card',
        'General Thinking Concepts': 'blue-card',
        'Numeracy': 'black-card',
        'Systems': 'purple-card',
        'Physical World': 'green-card',
        'The Biological World': 'orange-card',
        'Human Nature & Judgment': 'pink-card',
        'Microeconomics & Strategy': 'yellow-card',
        'Military & War': 'red-card'
      }
      return categoryClasses[props.model.category] || ''
    })
    
    const isYellowCard = computed(() => {
      return props.model.category === 'Microeconomics & Strategy'
    })
    
    const nextModel = () => {
      emit('onNext')
    }
    
    const previousModel = () => {
      emit('onPrevious')
    }
    
    const google = (model) => {
      const url = 'https://www.google.com/search?q=' + encodeURIComponent(model.name)
      window.open(url, '_blank')
    }
    
    return {
      cardClass,
      isYellowCard,
      nextModel,
      previousModel,
      google
    }
  }
}
</script>

<style lang="scss" scoped>
.model-card {
  .card-header {
    color: white;
  }
  
  &.cyan-card .card-header {
    background: #00BCD4;
  }
  
  &.blue-card .card-header {
    background: #2196F3;
  }
  
  &.black-card .card-header {
    background: black;
  }
  
  &.purple-card .card-header {
    background: #9C27B0;
  }
  
  &.green-card .card-header {
    background: #4CAF50;
  }
  
  &.orange-card .card-header {
    background: #FF9800;
  }
  
  &.red-card .card-header {
    background: #f44336;
  }
  
  &.yellow-card .card-header {
    background: #FFEB3B;
    color: #000;
  }
  
  &.pink-card .card-header {
    background: #E91E63;
  }
}
</style>

// src/components/model-card.tsx
'use client';

import { Button } from './ui/button';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { MentalModel } from '../types/mental-models';
import { Search } from 'lucide-react';

interface ModelCardProps {
  model: MentalModel;
  onNext: () => void;
  onPrevious: () => void;
}

// Category color mapping
const getCategoryColor = (category: string): string => {
  const colorMap: Record<string, string> = {
    'Logical Fallacies': 'border-cyan-500 bg-cyan-50',
    'General Thinking Concepts': 'border-blue-500 bg-blue-50',
    'Numeracy': 'border-green-500 bg-green-50',
    'Systems': 'border-yellow-500 bg-yellow-50',
    'Physical World': 'border-orange-500 bg-orange-50',
    'The Biological World': 'border-red-500 bg-red-50',
    'Human Nature & Judgment': 'border-purple-500 bg-purple-50',
    'Microeconomics & Strategy': 'border-pink-500 bg-pink-50',
    'Military & War': 'border-gray-500 bg-gray-50'
  };
  return colorMap[category] || 'border-gray-300 bg-gray-50';
};

export function ModelCard({ model, onNext, onPrevious }: ModelCardProps) {
  const handleGoogleSearch = () => {
    const searchQuery = encodeURIComponent(model.name);
    window.open(`https://www.google.com/search?q=${searchQuery}`, '_blank');
  };

  return (
    <Card className={`w-full max-w-2xl mx-auto ${getCategoryColor(model.category)}`}>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <div className="space-y-1">
          <CardTitle className="text-2xl font-bold">{model.name}</CardTitle>
          <p className="text-sm text-muted-foreground">{model.category}</p>
        </div>
        <Button
          variant="outline"
          size="icon"
          onClick={handleGoogleSearch}
          className="shrink-0"
        >
          <Search className="h-4 w-4" />
        </Button>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="text-sm leading-relaxed whitespace-pre-line">
          {model.description}
        </div>
        <div className="flex justify-between pt-4">
          <Button onClick={onPrevious} variant="outline">
            Back
          </Button>
          <Button onClick={onNext}>
            Next
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
